name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discordNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Discord notification
        uses: discord/send-message@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            A new push occurred in the repository.

            Commit message: ${{ github.event.head_commit.message }}
            Commit author: ${{ github.event.head_commit.author.name }}
            Commit URL: ${{ github.event.head_commit.url }}