name: Discord Notification

on:
  push:
    branches:
      - main  # 替换为你的主分支名称

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Discord Notification
        uses: appleboy/ssh-action@master
        with:
          command: |
            curl -H "Content-Type: application/json" -X POST -d '{"content": "Code pushed to repository: ${{ github.repository }}\nCommit message: ${{ github.event.head_commit.message }}\nPushed by: ${{ github.actor }}" }' {{ secrets.DISCORD_WEBHOOK_URL }}