name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discordNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set commit message
        id: commit
        run: echo "::set-output name=message::$(git log --format=%B -n 1 $GITHUB_SHA)"

      - name: Get current time
        id: current_time
        run: echo "::set-output name=time::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: Send Discord notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
              "content": "New push in the repository.",
              "username": "GitHub",
              "avatar_url": "https://example.com/avatar.png",
              "embeds": [
                {
                  "title": "Git Push Details",
                  "description": "Repo: ${{ github.repository }}\nOperator: ${{ github.actor }}\nTime: ${{ steps.current_time.outputs.time }}\nGit Commit Hash: ${{ github.sha }}\nContent: ${{ steps.commit.outputs.message }}",
                  "color": 16777215
                }
              ]
            }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}